import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'B7Web ReactJS Amigo Secreto',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className="bg-gray-950 text-gray-100">{children}</body>
    </html>
  )
}
